support re-running bash-plus + logv + delete_on_exit + temp_cp

diff --git a/bash-plus b/bash-plus
--- a/bash-plus
+++ b/bash-plus
@@ -32,6 +32,11 @@ success () {
   >&2 printf "   [ ${green}OK${neutral} ] $1 $2\n"
 }
 
+logv() {
+  [[ "$debug" != "" ]] && log $1
+}
+
+
 fatal () {
   error $2
   exit 1
@@ -119,24 +124,89 @@ is_CI(){
         return 1
     fi
 }
+#===================================================================
+# FUNCTION trap_add ()
+#
+# Purpose:  appends a command to a trap
+#
+# - 1st arg:  code to add
+# - remaining args:  names of traps to modify
+#
+# Example:  trap_add 'echo "in trap DEBUG"' DEBUG
+#
+# See: http://stackoverflow.com/questions/3338030/multiple-bash-traps-for-the-same-signal
+#===================================================================
+trap_add() {
+    trap_add_cmd=$1; shift || fatal "${FUNCNAME} usage error"
+    new_cmd=
+    for trap_add_name in "$@"; do
+        # Grab the currently defined trap commands for this trap
+        existing_cmd=`trap -p "${trap_add_name}" |  awk -F"'" '{print $2}'`
+
+        # Define default command
+        [ -z "${existing_cmd}" ] && existing_cmd="echo"
+
+        # Generate the new command
+        new_cmd="${existing_cmd};${trap_add_cmd}"
+
+        # Assign the test
+         trap   "${new_cmd}" "${trap_add_name}" || \
+                fatal "unable to add to trap ${trap_add_name}"
+    done
+}
+
+delete_on_exit() {
+  [[ "$1" == "" || "$1" == "/" ]] && fatal "Attempting to delete root directory"
+  logv "Deleting $1 on exit"
+  _delete_on_exit+=($1)
+  trap_add "_do_delete_on_exit" EXIT
+}
+
+_do_delete_on_exit() {
+  for i in "${_delete_on_exit[@]}"; do
+    rm -rf "$i"
+  done
+  _delete_on_exit=()
+}
+_delete_on_exit=()
+temp_cp() {
+  cp "$1" "$2"
+  delete_on_exit "$2"
+}
+
 timestamp=$(date +%s)
 ## END_OF_BASH_PLUS
-
-
-# python-scripts are copied to a bin directory without a link back to the python dist folder
-# we therefore embed the lib script and extract it at runtime
-# get the line that bash plus library ends in the current script
-LINE_NO="$(grep -n "END_OF_BASH_PLUS" $0 | head -n 1 | cut -d: -f1)"
-LIB_SCRIPT=$(cat $0 | head -n $LINE_NO)
-
-
 script=$1
+BASH_PLUS=$0
 sed=sed
 if is_mac ; then
   sed=gsed
 fi
 
-echo "$LIB_SCRIPT"
+cp $script $script.bak
+function finish() {
+  mv $script.bak $script
+}
+trap finish EXIT
+
+function remove_existing_bash_libs() {
+  LINE_NO="$(cat $script | awk '/END_OF_BASH_PLUS/{ print NR; exit }')"
+  LENGTH=$(wc -l $script | awk '{print $1}')
+  if [[ "$LINE_NO" != "" ]]; then
+    tail -n $(expr $LENGTH - $LINE_NO ) $script | sponge $script
+  fi
+}
+# python-scripts are copied to a bin directory without a link back to the python dist folder
+# we therefore embed the lib script and extract it at runtime
+function extract_bash_libs() {
+  # get the line that bash plus library ends in the current script
+  LINE_NO="$(cat $BASH_PLUS | awk '/END_OF_BASH_PLUS/{ print NR; exit }')"
+  cat $BASH_PLUS | head -n $LINE_NO
+}
+remove_existing_bash_libs
+extract_bash_libs
+
 docker run -it --rm -e PROGRAM=argbash -v "$(pwd):$(pwd)" -w $(pwd) matejak/argbash $script -o .$script
+# remove _arg_ prefix from all argument variables
 cat .$script | $sed 's|_arg_\(.*\)=|\1=|'
 rm -f .$script || true
